### ISSUE TITLE
Add library tests into prerelease CI build

### ISSUE THREAD

**Issue by RusinovAnton** [yola/eslint-plugin-yola#20]
At this moment it has been several releases with failed tests. Is it possible to run library tests before release?

**Comment by stefanor** [comment]
> At this moment it has been several releases with failed tests

Sounds like two problems:
1. We don't have a Jenkins job checking PRs, you should add one to https://github.com/yola/yolatools/blob/master/projects/jenkins-job-builder/jobs/tests/js_libs.yml
2. People aren't running tests locally. You should make that a habit.
