### ISSUE TITLE
Switch this repo to Github Actions

### ISSUE THREAD

**Issue by fr33l** [yola/eslint-plugin-yola#52]
Since this is a public repo it makes sense to have test jobs configured on Github actions. 

To do:

- Create Github actions workflow that will: 
 - Trigger test job upon PR creation
 - It should support nvm and use node version specified in .nvmrc in this repo. 
 - Run tests with npm test.

**Comment by yanaddn** [comment]
All done https://github.com/yola/eslint-plugin-yola/actions
